/*
=============================================================================
  SNOWFLAKE PARTNER ENABLEMENT - LISBON
  Script 00: Environment Setup
  
  This script creates the demo database, schemas, warehouses, and roles
  needed for the Partner Enablement session.
  
  Run as: ACCOUNTADMIN
=============================================================================
*/

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE DATABASE PARTNERS_LISBON_DEMO;

CREATE SCHEMA PARTNERS_LISBON_DEMO.RAW;
CREATE SCHEMA PARTNERS_LISBON_DEMO.ANALYTICS;
CREATE SCHEMA PARTNERS_LISBON_DEMO.GOVERNANCE;

CREATE OR REPLACE WAREHOUSE PARTNERS_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse for Partner Enablement session - Lisbon';

CREATE OR REPLACE WAREHOUSE PARTNERS_WH_MEDIUM
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Medium warehouse for performance comparison demo';

USE WAREHOUSE PARTNERS_WH;
USE DATABASE PARTNERS_LISBON_DEMO;
USE SCHEMA RAW;

CREATE OR REPLACE ROLE ANALYST_ROLE
  COMMENT = 'Role for business analysts - limited access';

CREATE OR REPLACE ROLE ENGINEER_ROLE
  COMMENT = 'Role for data engineers - broader access';

GRANT ROLE ANALYST_ROLE TO ROLE SYSADMIN;
GRANT ROLE ENGINEER_ROLE TO ROLE SYSADMIN;

GRANT USAGE ON DATABASE PARTNERS_LISBON_DEMO TO ROLE ANALYST_ROLE;
GRANT USAGE ON DATABASE PARTNERS_LISBON_DEMO TO ROLE ENGINEER_ROLE;

GRANT USAGE ON ALL SCHEMAS IN DATABASE PARTNERS_LISBON_DEMO TO ROLE ANALYST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PARTNERS_LISBON_DEMO TO ROLE ENGINEER_ROLE;

GRANT USAGE ON WAREHOUSE PARTNERS_WH TO ROLE ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE PARTNERS_WH TO ROLE ENGINEER_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA PARTNERS_LISBON_DEMO.RAW TO ROLE ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PARTNERS_LISBON_DEMO.ANALYTICS TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PARTNERS_LISBON_DEMO.ANALYTICS TO ROLE ENGINEER_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA PARTNERS_LISBON_DEMO.RAW TO ROLE ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PARTNERS_LISBON_DEMO.ANALYTICS TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PARTNERS_LISBON_DEMO.ANALYTICS TO ROLE ENGINEER_ROLE;

SELECT 'Environment setup complete!' AS STATUS;
